application:
  email:
    sendgrid:
      apikey: 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
  initDB: false
  initUsers: false
  mail:
    enabled: false
  maxReservationsPerDay: 2
  objectstorage:
    avatarsbucket: gabrigiunchiavatar
    cos:
      apikeyid: aenGMJUEKvU5MedOZkPZw57AJhjUJflrXbec0AFgyzOD
      authendpoint: https://iam.cloud.ibm.com/identity/token
      crn: crn:v1:bluemix:public:iam-identity::a/da6c0accc4b541c3a95e2e3cc3958c9a::serviceid:ServiceId-f51fb9cf-8d7d-406f-aedb-0888e3415767
      host: s3.eu-de.cloud-object-storage.appdomain.cloud
      location: eu-de
    gymphotosbucket: gymphotos
  reservationThresholdInDays: 14
  version: 3.0.6
  zoneId: UTC
google:
  apikey: AIzaSyBiClW-tzn_XUpFDNs6c5PjwGtE61xaW6A
security:
  jwt:
    token:
      expireHours: 1460
      secret-key: dnsjndajksnjxnsajn6786
spring:
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    hikari:
      max-active: 5
    max-active: 5
    password: 33m1cw7r4dc9j+6h
    tomcat:
      max-active: 5
    url: jdbc:db2://dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net:50000/BLUDB
    username: mmj32786
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: MMJ32786
        dialect: org.hibernate.dialect.DB2Dialect
        jdbc:
          time_zone: UTC